### ISSUE TITLE
Automatic creation/commit of cpanfile interferes with multiple operations

### ISSUE THREAD

**Issue by haarg** [RsrchBoy/dist-zilla-pluginbundle-rsrchboy#4]
The bundle causes an automatic creation of a cpanfile, and then commits it.  This is triggered for listdeps in a fresh clone, which in addition to causing a bad commit that must be removed, breaks the ability to pipe the output to cpanm.

Here is an example of the result of this:
https://travis-ci.org/RsrchBoy/Dist-Zilla-Plugin-ContributorsFromGit/jobs/12474477

**Comment by RsrchBoy** [comment]
Looks like I accidentally fixed this a while back.  Closing :)
